In [ ]:
#Srinitish Srinivasan
#21BAI1394

In [22]:
from keras.models import Sequential 
from keras.layers import Dense
from sklearn.model_selection import StratifiedKFold
import numpy as np
import pandas as pd 
import keras

In [23]:
dataset=pd.read_csv("/Volumes/T7 Shield/Smudge/Datasets/diabates/diabetes.csv")

In [24]:
dataset

     Pregnancies  Glucose  ...  Age  Outcome
0              6      148  ...   50        1
1              1       85  ...   31        0
2              8      183  ...   32        1
3              1       89  ...   21        0
4              0      137  ...   33        1
..           ...      ...  ...  ...      ...
763           10      101  ...   63        0
764            2      122  ...   27        0
765            5      121  ...   30        0
766            1      126  ...   47        1
767            1       93  ...   23        0

[768 rows x 9 columns]

In [26]:
#X and Y
X=np.array(dataset.drop('Outcome',axis=1))
Y=np.array(dataset['Outcome'])

In [29]:
kfold=StratifiedKFold(n_splits=10,shuffle=True,random_state=7)
tot_scores=[]

for train,test in kfold.split(X,Y):
    model=Sequential()
    model.add(Dense(12,input_dim=8,kernel_initializer='uniform',activation='relu'))
    model.add(Dense(1,kernel_initializer='uniform',activation='sigmoid'))

    model.compile(loss=keras.losses.BinaryCrossentropy(),metrics=keras.metrics.BinaryAccuracy(),optimizer='adam')

    model.fit(X[train],Y[train],epochs=100,batch_size=10,verbose=0)

    scores=model.evaluate(X[test],Y[test],verbose=0)
    tot_scores.append(scores[1]*100)

In [30]:
sum(tot_scores)/len(tot_scores)

72.79391527175903